name: mulabbi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  prayers_times: ^0.0.6
  hijri: ^3.0.0
  http: ^1.2.1
  geolocator: ^12.0.0
  intl: any
  hijri_picker: ^3.0.0
  provider: ^6.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  get: ^4.7.2
  arabic_numbers: ^1.0.0
  fluentui_system_icons: ^1.1.273
  adhan: ^2.0.0+1
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^18.0.1
  enum_to_string: ^2.2.1
  shared_preferences: ^2.5.3
  device_info_plus: ^11.4.0
  jhijri: ^1.0.0
  internet_connection_checker_plus: ^2.7.2
  share_plus: ^11.0.0
  timeago: ^3.7.1
  lottie: ^3.0.0
  responsive_sizer: ^3.3.1
  quran: ^1.1.0
  google_fonts: ^4.0.4
  youtube_player_flutter: ^8.1.1
  dio: ^5.8.0+1
  supabase_flutter: ^2.9.1
  flutter_lints: ^5.0.0
  flutter_compass: ^0.8.1
  adhan_dart: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/data/nusk_details.json
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-VariableFont_slnt,wght.ttf
          weight: 700

    - family: AyatQuran2
      fonts:
        - asset: assets/fonts/ayat_quran_2/AyatQuran2.ttf

    - family: KFGQPC-HafsEx1
      fonts:
        - asset: assets/fonts/hafs/KFGQPC-HafsEx1.ttf

    - family: AlNile
      fonts:
        - asset: assets/fonts/nile/Al_Nile.ttc

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
